name: Lint

on:
  workflow_call:
    inputs:
      node-version:
        description: Node version
        required: false
        type: string
        default: '24.x'
      biome-version:
        description: Biome version
        required: false
        type: string
        default: latest
      working-directory:
        description: Directory containing package.json
        required: false
        type: string
        default: '.'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: toweray/ci-cookbook/actions/setup-node@trunk
        with:
          node-version: ${{ inputs.node-version }}
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2.7.1
        with:
          version: ${{ inputs.biome-version }}

      - name: Run Biome
        run: biome ci
