name: Validate Renovate config

on:
  pull_request:
    paths:
      - renovate.json
      - renovate-config.json
  push:
    branches:
      - trunk
      - master
    paths:
      - renovate.json
      - renovate-config.json

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate renovate-config.json
        run: npx --yes --package renovate -- renovate-config-validator renovate-config.json

      - name: Validate renovate.json
        run: npx --yes --package renovate -- renovate-config-validator renovate.json
